### ISSUE TITLE
Suggestions for snippet examples.

### ISSUE THREAD

**Issue by jrusbatch** [jrusbatch/compilify#24]
The site needs good example snippets to demonstrate its capabilities to new users. If you wrote a cool snippet, post a link to it here! Bonus points if it's documented!

**Comment by fekberg** [comment]
A suggestion to this is to add a tab on each submitted snippet called "documentation". So snippets can be documented in a wiki-fasion. In the long run, if there are multiple classes on a submission, it can be nice with some domain specific documentation.

Just a thought.

**Comment by jrusbatch** [comment]
Would it be possible to pull XML documents out of the code with Roslyn?

**Comment by fekberg** [comment]
I don't see why not, but haven't tried it.

**Comment by lmaran** [comment]
http://compilify.net/pm/5
My snippet is about a  Generate Slug (including accent removing) for a given phrase.

**Comment by jrusbatch** [comment]
@lmaran, it's been added. Thanks!

**Comment by rumnha** [comment]
My example snippet - Simple string compression with regex - https://compilify.net/2m0/6

**Comment by rumnha** [comment]
You have a mention in a comment on Codeproject (http://www.codeproject.com/Articles/583477/Csharp-Snippet-Sharing-with-Roslyn-and-SignalR?msg=4551506#xx4551506xx). Brian is doing similar app in windows azure challenge

**Comment by jrusbatch** [comment]
@rumnha Thanks!
