### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by JimmyLahaie** [jrusbatch/compilify#28]
Uploading dll that the code will use might cause a major security issue.
But it will be nice if we can select popular library to compile with our code.
For example
- nUnit
- Ninject
- AutoMapper
- EntityFramwork
- ...

**Comment by jrusbatch** [comment]
Allowing the execution of code code contained in uploaded assemblies would be a security issue. I thought about allowing assembly uploads for validation purposes only, but when you start to think about storing and any legalities that might apply to closed-source assemblies I quickly walked away from the idea.

Allowing users to reference assemblies that are available on Nuget, though... that's interesting to think about. 

I'm thinking it would take quite a bit of time for a worker to gather all the libraries necessary for a single snippet's execution, though...

**Comment by khalidabuhakmeh** [comment]
I'd probably do something like http://jsfiddle.net/. Where you get a dropdown of libraries that are available to you to use.
