### ISSUE TITLE
Refactor Home/Index

### ISSUE THREAD

**Issue by jrusbatch** [jrusbatch/compilify#33]

**Comment by khalidabuhakmeh** [comment]
I think that's a good idea. +1

possible refactored controllers:
- Posts (Index, Show, Latest, Save, Validate)
- Snippets (library of packaged samples, including the default person one)
- Home / Marketing  ( About, Wiki, Limitations, etc...)

**Comment by jrusbatch** [comment]
I've thought about moving methods related to the `Post` class into an `ApiController`. Still undecided on that, though.

What about making the default example an entry in the DB, and then specify its slug via the web.config? If no default slug is specified, leave the editors blank? I'm not sure the interface is intuitive enough for that, though.

**Comment by khalidabuhakmeh** [comment]
If there is going to be a set of examples in the database, we could just pick one at random. That would help people see what's possible. You could also tie that into a random snippet button.

The random snippet button will find you a random public snippet and load it.

**Comment by jrusbatch** [comment]
That's possible. I don't want to put too much effort into producing examples on page load... I'd rather not need examples to demonstrate how it works.
