### ISSUE TITLE
Predefine a class that acts like Console

### ISSUE THREAD

**Issue by khalidabuhakmeh** [jrusbatch/compilify#34]
It would be nice to be able to use Console in the execute window. 

```
Console.WriteLine("debugging")
```

**Comment by jrusbatch** [comment]
For what purpose?

**Comment by khalidabuhakmeh** [comment]
For debugging mainly. It feels a little more natural than having to create a Result class  in the "Define" section.

**Comment by jrusbatch** [comment]
I think [this technique](http://blogs.microsoft.co.il/blogs/sasha/archive/2011/10/25/lap-around-roslyn-ctp-syntax-rewriting-with-symbol-information.aspx) would accomplish the goal: use an implementation of Roslyn's `SyntaxRewriter` class to replace the appropriate calls to methods in the `Console` class with calls to a custom class that evaluates the input and stores the result in a list. The contents of that list could be dumped to the result panel.

**Comment by jrusbatch** [comment]
Actually, I think the technique @ermau demonstrates on his [blog](http://ermau.com/making-instant-c-viable-part-1/) might be a better solution. I need to investigate whether or not it would work the current architecture, though.
