### ISSUE TITLE
Add search capability

### ISSUE THREAD

**Issue by jrusbatch** [jrusbatch/compilify#36]
Allow users to search for snippets. Potential search keywords could include:
- User-defined tags
- Symbols referenced from external libraries

There should also be a flag to allow users to let users prevent their posts from being included in search results. Posts that were submitted before the search functionality is implemented should be excluded from the results by default.

**Comment by dpen2000** [comment]
Hi Justin, do you still want to do this?

**Comment by jrusbatch** [comment]
@dpen2000 I'm not sure this is valid anymore. When I created this issue I thought Compilify would be used for sharing code snippets, but it looks like it has more use as an online scratchpad for C#. Having some kind of "go to definition" capability within a snippet might be useful though.

**Comment by dpen2000** [comment]
@jrusbatch Happy to have a go at that for you. Would that be for navigating between pieces of code within a Complify page or for linking to msdn for a member? I'd be in favour of the latter for .net framework classes etc. Could you create an issue for this?

**Comment by jrusbatch** [comment]
@dpen2000 Created #67 for this.
