### ISSUE TITLE
allow users to optionally reference predefined libraries

### ISSUE THREAD

**Issue by prabirshrestha** [jrusbatch/compilify#43]
something like http://jsfiddle.net/ which includes list of well known libraries like jquery, mootools.

You can then add libraries like Facebook C# SDK.  https://github.com/facebook-csharp-sdk/facebook-csharp-sdk and then we can use classes from Facebook library. 

There are lots of time when I need to test the fb request and test on the browser without creating a new console app.

**Comment by jrusbatch** [comment]
There's another issue open requesting the ability to reference third-party libraries. I think it would be really useful if users could "install" packages from NuGet directly into their posts. That would let you reference the library, but the actions you perform with it would still be limited by the sandbox your code is executed in. Network requests would result in a security exception.

**Comment by jrusbatch** [comment]
Making issue #28 the primary issue for this.
