### ISSUE TITLE
Support latest Roslyn CTP

### ISSUE THREAD

**Issue by rarous** [jrusbatch/compilify#49]
Move to Roslyn CTP3 to support C# 3.0 features.

**Comment by nberardi** [comment]
What features of C# 3.0 are you missing?

**Comment by nberardi** [comment]
Don't bother upgrading.  They are distributing .NET 4.5 compiled libraries as .NET 4.0 libraries in the NuGet package.  Causing me a major headache.

**Comment by rarous** [comment]
Damn inplace upgrade...

**Comment by rarous** [comment]
Missing features. You got me. Last time I tried Compilify LINQ was not working, now it seems it's ok. Sorry.

**Comment by nberardi** [comment]
LINQ missing was most likely related to a namespace not being included.

**Comment by rarous** [comment]
But output was complaining about Expression trees.

**Comment by jrusbatch** [comment]
@rarous Can you link to a post that reproduces the issues you're referring to?

**Comment by jrusbatch** [comment]
@nberardi Compilify is already updated to .NET 4.5, so that won't be a problem.

**Comment by nberardi** [comment]
@JRusbatch didn't see that commit you made a couple weeks back.

**Comment by jrusbatch** [comment]
Updated Roslyn to CTP3 with commit 2f6ebc6ac79aa35d7f2f5fa7d4e1b3ca1455ec21.
