### ISSUE TITLE
Require SSL

### ISSUE THREAD

**Issue by jrusbatch** [jrusbatch/compilify#6]
Users should be redirected to use the HTTPS protocol if they attempt to access any resource without it.

**Comment by khalidabuhakmeh** [comment]
Are you sure you don't want to fix this one? It is pretty easy to accomplish. It just can get a little hairy with jquery, since you can't do ajax request across different protocols.

**Comment by jrusbatch** [comment]
I wasn't sure how much load I would get, or how much demand there would be for SSL, so I couldn't justify the additional cost for a good certificate. Without any kind of authentication, is there a compelling reason to reopen it?

**Comment by khalidabuhakmeh** [comment]
the only reason I would reopen it, is if you want to create a community around snippets. Like "Khalid" wrote this snippet and wants to share it with you "Justin.".

Profiles and Login would most likely need to be secured behind SSL.

**Comment by jrusbatch** [comment]
Agreed. I think it's definitely something to reconsider when some kind of membership is on the horizon.
