### ISSUE TITLE
500 Internal server error on save

### ISSUE THREAD

**Issue by collinsauve** [jrusbatch/compilify#65]
Whenever I save today, I get a 500.
This seems to be regardless of content - even the default content throws a 500.

**Comment by jrusbatch** [comment]
This appears to have been caused by an upgrade performed by MongoHQ that broke compatibility with the version of mongocsharpdriver installed.

**Comment by jrusbatch** [comment]
Fixed in 8c2e1e95253a732512e2dcfe31b08099a183bf3a.
