### ISSUE TITLE
Enable the user to navigate to definition

### ISSUE THREAD

**Issue by jrusbatch** [jrusbatch/compilify#67]
When the user executes the "Go To Definition" command on something declared in the .NET framework, the MSDN documentation for that member should be opened in a new browser tab. Otherwise, the cursor should be moved to the definition in the user's code. If the cursor is already at the definition, or if the definition cannot be resolved, we should do nothing.

**Comment by jrusbatch** [comment]
Also, it should be clear to the user that attempting to navigate to the definition of a framework member will open up a new browser tab.

**Comment by dpen2000** [comment]
I'll take a look at this for you. Do you have an opinion on how this should be invoked? I think perhaps a combination of a button at the top (maybe at the top of each code pane) combined with a shortcut might be good.

**Comment by jrusbatch** [comment]
@dpen2000 I agree. F12 would make sense since that's what Visual Studio uses - if it's possible to bind to that.

**Comment by dpen2000** [comment]
> Also, it should be clear to the user that attempting to navigate to the definition of a framework member will open up a new browser tab.

Could this merely be some static text saying "Attempting to navigate to the definition of a framework member will open up a new browser tab."? Or how did you envision this working?
If it was wanting to dynamically indicate to the user that the current focused item would cause a new browser tab to open, we'd probably want to know in advance the locations of framework members.

I think I have two possible implementation approaches in general. One is generating a map of cursor positions to their definitions on every Validate and returning this back. This makes it easy to tell the user that clicking Go to Definition would result in a new browser window. It's also means we can move the user's cursor within documents quickly. But the disadvantage would be larger code will result in a bigger map being sent back on each Validate.
The other approach I'm considering is to go to server for the semantic information about the syntax the user has their cursor over only when they invoke the Go to Definition command. This would result in slower operation but is perhaps more efficient.
Are either of this approaches how you'd envision it working? I'm leaning towards the latter approach now.
